;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
      TeX-insert-backslash
      end-of-visual-line
      hungry-delete-backward
      hungry-delete-forward
      indent-for-tab-command
      org-self-insert-command
      pvj/smart-move-to-line-beginning
      ))

(setq mc/cmds-to-run-once
      '(
      helm-M-x
      ))
