#+STARTUP: showall

* My Emacs configuration

[[https://travis-ci.org/peterwvj/emacs.d.svg?branch=master]]

I have developed a set of configuration files that allow me to
efficiently carry out my daily work in Emacs. This repository contains
these configuration files in the hope that they will be useful to
others.

* Repository structure

The Emacs initialisation file, =init.el=, is located in the root of
this repository. It loads several other configuration files contained
in the =elisp= folder. As an example, =elisp/mu4e-config.el= contains
my [[http://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]] (email client) configuration.

* Configuration highlights

The configuration files are used to:

- Manage multiple email accounts using mu4e
  - To synchronise and filter emails I use OfflineIMAP and
    [[https://github.com/lefcha/imapfilter][imapfilter]]. I keep my OfflineIMAP and imapfilter configuration
    files in one of my other [[https://github.com/peterwvj/offlineimap-config-pvj/][repositories]].
- Work with LaTeX using [[https://www.gnu.org/software/auctex/][AUCTeX]] and [[https://github.com/politza/pdf-tools][pdf-tools]]
- Configure my terminal, =eshell=
- Manage Git repositories
- Etc.

* Using the configuration

Comprehensive Emacs configurations usually take a bit of time to
load. To address this, I launch Emacs as a /daemon/ on system startup,
and every time I need to use Emacs I launch it as a /client/. In this
way, the configuration only needs to be loaded once during system
startup.

To launch Emacs as a daemon execute:

#+BEGIN_SRC bash
emacs --daemon
#+END_SRC

In addition, I use a function =e= to launch Emacs as a client:

#+BEGIN_SRC bash
function e {
  emacsclient -c -a emacs "$@" > /dev/null 2>&1 & disown
}
#+END_SRC

Now, to open a file with Emacs you simply run:

#+BEGIN_SRC bash
e <file>
#+END_SRC

* Testing the configuration

I use [[https://travis-ci.org/][Travis CI]] to test that the configuration works with the most
recent versions of Emacs. Specifically, I check that it loads with
Emacs 24.5, 25.1 and bleeding edge snapshots. The approach that I take
to testing that the configuration loads successfully is inspired by
that of [[https://github.com/purcell/emacs.d][Steve Purcell]].

