#+STARTUP: showall

* My Emacs configuration

[[https://travis-ci.org/peterwvj/emacs.d.svg?branch=master]]

I have developed a set of configuration files that allow me to
efficiently carry out my daily work in Emacs. This repository contains
these configuration files in the hope that they will be useful to
others.

* Quick start

To install this Emacs configuration run:

#+BEGIN_SRC bash
git clone git@github.com:peterwvj/emacs.d.git ~/.emacs.d
#+END_SRC

* Using the configuration

Comprehensive Emacs configurations usually take a bit of time to
load. To address this, I launch Emacs as a /daemon/ on system startup,
and every time I need to use Emacs I launch it as a /client/. In this
way, the configuration only needs to be loaded once during system
startup.

To launch Emacs as a daemon execute:

#+BEGIN_SRC bash
emacs --daemon
#+END_SRC

In addition, I use a function =e= to launch Emacs as a client:

#+BEGIN_SRC bash
function e {
  emacsclient -c "$@" > /dev/null 2>&1 & disown
}
#+END_SRC

Now, to open a file with Emacs you simply run:

#+BEGIN_SRC bash
e <file>
#+END_SRC

* Testing the configuration

I use [[https://travis-ci.org/][Travis CI]] to test that the configuration works with the most
recent versions of Emacs. Specifically, I check that it loads with
Emacs 24.5, 25.1 and bleeding edge snapshots. The approach that I take
to testing that the configuration loads successfully is inspired by
that of [[https://github.com/purcell/emacs.d][Steve Purcell]].

